name: test

on:
  push

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: install depencies
      run: pip install -r requirements.txt
    - name: test download
      run: python download.py 周杰伦
    - name: test analyse
      run: python analyse.py 周杰伦 --test

