name: test

on:
  push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, macOS-latest, ubuntu-16.04, ubuntu-18.04, ubuntu-latest, windows-latest]
        python: ['3.5', '3.6', '3.7']

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
        architecture: 'x64'
    - name: install depencies
      run: pip install -r requirements.txt
    - name: test download
      run: python download.py 周杰伦
    - name: test analyse
      run: python analyse.py 周杰伦 --test

